flaskapp/flaskapp/views/content.py
from flask import Blueprint, render_template


bp = Blueprint('content', __name__)


@bp.route('/', methods=['GET'])
def home():
    """GET /: render homepage
    """
    return render_template('/content/home.html')


@bp.route('/feedback', methods=['GET', 'POST'])
def feedback():
    """GET|POST /feedback: feedback form handler
    """
    form = FeedbackForm()
    if form.validate_on_submit():
        # TODO: send feedback to contact@example.com
        return 'ok'

    return render_template('/content/feedback.html', form=form)

flaskapp/flaskapp/templates/shared-email/base-layout.html
{% extends "/shared-email/skeleton.html" %}


{% block HEADERTAGS %}
<style data-premailer="ignore">
  {{ h.Markup(h.pkg_resources.resource_string('flaskapp', '/static/vendor/mui-0.9.12/email/mui-email-styletag.css')) }}
</style>
<style>
  {{ h.Markup(h.pkg_resources.resource_string('flaskapp', '/static/vendor/mui-0.9.12/email/mui-email-inline.css')) }}
</style>
<style>
  body, .mui-body {
    background-color: #eee;
    font-size: 15px;
  }

  .mui-container-fixed, .mui-container {
    padding-top: 15px;
    padding-bottom: 15px;
  }

  #logo-wrapper {
    padding-bottom: 7px;
  }

  #footer {
    font-size: 13px;
    color: #888;
  }

  #footer a {
    color: #888;
  }

  #footer td {
    padding-top: 5px;
  }

  .footer-contact-link {
    text-decoration: underline;
  }
</style>
{% endblock %}


{% block HTML %}
<table class="mui-body" cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td>
      <center>
        <!--[if mso]><table><tr><td class="mui-container-fixed"><![endif]-->
        <div class="mui-container">
          <table cellpadding="0" cellspacing="0" border="0" width="100%">
            <tr>
              <td id="logo-wrapper" class="mui--text-center">
                <a class="mui--text-headline mui--text-dark" href="{{ url_for('content.home') }}">Flaskapp</a>
              </td>
            </tr>
          </table>
          <table cellpadding="0" cellspacing="0" border="0" width="100%">
            <tr>
              <td class="mui-panel">{% block PANEL_CONTENT %}{% endblock %}</td>
            </tr>
          </table>
          {{ footer_html() }}
        </div>
        <!--[if mso]></td></tr></table><![endif]-->
      </center>
    </td>
  </tr>
</table>
{% endblock %}


{% macro footer_html() %}
<table id="footer" cellpadding="0" cellspacing="0" border="0" width="100%">
  <tr>
    <td>
      <div>&copy;{{h.datetime.datetime.today().year}} Flaskapp</div>
      <div><a class="footer-contact-link" href="mailto:contact@flaskapp.com">contact@flaskapp.com</a></div>
    </td>
  </tr>
</table>
{% endmacro %}

flaskapp/flaskapp/templates/shared-email/skeleton.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />
    {% block HEADERTAGS %}{% endblock %}
  </head>
  <body>
    {% block HTML %}{% endblock %}
  </body>
</html>